universe              = vanilla
executable            = scripts/run_condor_job.sh
should_transfer_files = NO
getenv                = True
request_cpus          = 1
request_memory        = 2500 MB
CHUNK                 = $(Process)
arguments             = $(CHUNK)
output                = <sample_dir>/logs/condor_$(ClusterId).$(Process).out
error                 = <sample_dir>/logs/condor_$(ClusterId).$(Process).err
log                   = <sample_dir>/logs/condor_$(ClusterId).log
queue <n_jobs>
