#!/usr/bin/env python3
"""Convolve fixed detector-response points with ordinary-trigger readouts.

The detector response and trigger timeline remain independent inputs.  A
timeline readout at relative BX ``b`` uses the response generated by shifting
the signal by ``-b`` BX relative to a fixed readout.  No detector window or
trigger decision is changed here.
"""

import argparse
import json
from collections import defaultdict
from pathlib import Path


def _parse_offset_spec(spec):
    offset_text, separator, path = spec.partition("=")
    if not separator or not offset_text or not path:
        raise ValueError(f"expected INTEGER=JSON, got {spec!r}")
    try:
        offset = int(offset_text)
    except ValueError as error:
        raise ValueError(f"response offset must be an integer, got {offset_text!r}") from error
    return offset, path


def _load_reports(specs, schema_version, kind, phase_ns=0.0):
    reports = {}
    paths = {}
    for spec in specs:
        offset, path = _parse_offset_spec(spec)
        if offset in reports:
            raise ValueError(f"duplicate {kind} response offset {offset}")
        with open(path, encoding="utf-8") as input_file:
            report = json.load(input_file)
        if report.get("schema_version") != schema_version:
            raise RuntimeError(
                f"{path} has {kind} schema {report.get('schema_version')!r}, "
                f"expected {schema_version}"
            )
        timing = report.get("simhit_reference_timing")
        if not timing:
            raise RuntimeError(f"{path} lacks embedded same-SimHit timing provenance")
        if int(timing["bx_offset"]) != offset:
            raise RuntimeError(
                f"{path} is labeled offset {offset}, but EDM provenance says "
                f"{timing['bx_offset']}"
            )
        if abs(float(timing["phase_ns"]) - phase_ns) > 1.0e-9:
            raise RuntimeError(
                f"{path} has phase_ns={timing['phase_ns']}, expected {phase_ns}"
            )
        reports[offset] = report
        paths[offset] = path
    return reports, paths


def _discover_response_specs(directory, filename, phase_ns=0.0):
    specs = []
    for path in sorted(Path(directory).glob(f"*/{filename}")):
        with path.open(encoding="utf-8") as input_file:
            report = json.load(input_file)
        timing = report.get("simhit_reference_timing")
        if not timing:
            raise RuntimeError(f"{path} lacks embedded same-SimHit timing provenance")
        if abs(float(timing["phase_ns"]) - phase_ns) > 1.0e-9:
            continue
        specs.append(f"{int(timing['bx_offset'])}={path}")
    return specs


def _load_timeline(path):
    metadata = None
    records = defaultdict(list)
    with open(path, encoding="utf-8") as input_file:
        for line_number, line in enumerate(input_file, 1):
            if not line.strip():
                continue
            record = json.loads(line)
            if record.get("record_type") == "metadata":
                if metadata is not None:
                    raise RuntimeError(f"multiple metadata records in {path}")
                metadata = record
            elif record.get("record_type") == "timeline_bx":
                records[int(record["signal_event_index"])].append(record)
            else:
                raise RuntimeError(f"unknown record type at {path}:{line_number}")
    if metadata is None or metadata.get("schema") != "shift-zero-bias-trigger-timeline":
        raise RuntimeError(f"missing SHIFT trigger-timeline metadata in {path}")
    if metadata.get("schema_version") != 1:
        raise RuntimeError(f"unsupported trigger-timeline schema in {path}")
    return metadata, records


def _muon_key(event, muon):
    return (
        int(event["run"]), int(event["lumi"]), int(event["event"]),
        int(muon["event_id"]["raw"]), int(muon["track_id"]),
    )


def _index_muons(report):
    result = []
    for event in report["events"]:
        result.append({_muon_key(event, muon): muon for muon in event["signal_muons"]})
    return result


def _validate_response_identity(reports, kind):
    offsets = sorted(reports)
    reference = reports[offsets[0]]
    reference_index = _index_muons(reference)
    for offset in offsets[1:]:
        observed_index = _index_muons(reports[offset])
        if len(observed_index) != len(reference_index):
            raise RuntimeError(f"{kind} response offset {offset} has a different event count")
        for event_index, (expected, observed) in enumerate(
            zip(reference_index, observed_index)
        ):
            if set(expected) != set(observed):
                raise RuntimeError(
                    f"{kind} response offset {offset}, event index {event_index} "
                    "has different signal-muon identities"
                )
            if kind == "capture":
                for key in expected:
                    for subsystem, expected_values in expected[key]["subdetectors"].items():
                        observed_values = observed[key]["subdetectors"][subsystem]
                        if (
                            expected_values["simhits"] != observed_values["simhits"]
                            or expected_values["simhit_non_timing_sha256"]
                            != observed_values["simhit_non_timing_sha256"]
                        ):
                            raise RuntimeError(
                                f"capture response offset {offset}, event index {event_index}, "
                                f"track {key[4]}, subsystem {subsystem} has different "
                                "non-timing SimHits"
                            )
    return reference_index


def _candidate_l1a(record):
    decisions = record.get("candidate_decisions")
    if not decisions:
        return False
    blocks = decisions.get("l1_by_bx", {}).get("0", [])
    return any(bool(block.get("final_or")) for block in blocks)


def _stored_by_hlt(record):
    decisions = record.get("candidate_decisions") or {}
    return bool(decisions.get("hlt_accepted"))


def _readout_sets(records, available_offsets, allow_incomplete_grid=False):
    candidate = set()
    raw = set()
    persisted = set()
    details = []
    uncovered = []
    for record in records:
        if not record.get("analysis_window") or not _candidate_l1a(record):
            continue
        timeline_bx = int(record["timeline_bx"])
        response_offset = -timeline_bx
        if response_offset not in available_offsets:
            uncovered.append(timeline_bx)
            continue
        candidate.add(response_offset)
        accepted = record.get("readout_after_trigger_rules")
        if accepted is None:
            raise RuntimeError(
                "timeline is pre-rule: readout_after_trigger_rules is null; "
                "generate it with --trigger-rule-mode run3"
            )
        if accepted:
            raw.add(response_offset)
            if _stored_by_hlt(record):
                persisted.add(response_offset)
        details.append(
            {
                "timeline_bx": timeline_bx,
                "response_signal_bx_offset": response_offset,
                "accepted_after_trigger_rules": bool(accepted),
                "stored_by_hlt_proxy": bool(accepted and _stored_by_hlt(record)),
                "source": record.get("source"),
                "hlt_accepted": (record.get("candidate_decisions") or {}).get(
                    "hlt_accepted", []
                ),
                "trigger_rule_decision": record.get("trigger_rule_decision"),
            }
        )
    if uncovered and not allow_incomplete_grid:
        raise RuntimeError(
            "detector-response grid does not cover candidate L1A timeline BX: "
            + ", ".join(str(value) for value in sorted(set(uncovered)))
        )
    return candidate, raw, persisted, details, uncovered


def _digi_spatial_channels(muon, field):
    return {
        (subsystem, *channel)
        for subsystem, values in muon["subdetectors"].items()
        for channel in values[field]
    }


def _lct_spatial_channels(muon, field):
    fields = ("chamber_id", "track_number", "quality", "key_wire", "strip", "bend")
    return {tuple(item[name] for name in fields) for item in muon["CSC"][field]}


def _digi_bx_split_evidence(muons_by_offset):
    result = {}
    for offset, muon in muons_by_offset.items():
        samples_by_subsystem = {}
        for subsystem in ("RPC", "GEM"):
            samples = sorted(
                int(sample)
                for sample, count in muon["subdetectors"][subsystem][
                    "matched_samples"
                ].items()
                if count
            )
            if samples:
                samples_by_subsystem[subsystem] = samples
        if len({sample for samples in samples_by_subsystem.values() for sample in samples}) > 1:
            result[offset] = samples_by_subsystem
    return result


def _stage_sets(muons_by_offset, expected_field, stored_field, extractor):
    expected = set()
    stored = {}
    for offset, muon in muons_by_offset.items():
        expected |= extractor(muon, expected_field)
        stored[offset] = extractor(muon, stored_field)
    return expected, stored


def _selected_union(stored, offsets):
    return set().union(*(stored[offset] for offset in offsets)) if offsets else set()


def _capture_classification(
    expected, stored, candidate_offsets, selected_offsets, bx_split_offsets=()
):
    if not expected:
        return "no_detector_content"
    for offset in selected_offsets:
        if expected <= stored[offset]:
            return (
                "split_within_readout"
                if offset in bx_split_offsets
                else "complete_one_readout"
            )
    selected_union = _selected_union(stored, selected_offsets)
    if expected <= selected_union:
        return "split_across_readouts"
    candidate_union = _selected_union(stored, candidate_offsets)
    if candidate_union - selected_union:
        return "partial_trigger_rule_loss"
    if selected_union:
        return "partial_electronics_loss"
    return "no_readout"


def _stage_metrics(
    expected, stored, candidate, raw, persisted, bx_split_offsets=()
):
    candidate_union = _selected_union(stored, candidate)
    raw_union = _selected_union(stored, raw)
    persisted_union = _selected_union(stored, persisted)
    return {
        "expected_spatial_objects": len(expected),
        "stored_spatial_objects_by_response_offset": {
            str(offset): len(items) for offset, items in sorted(stored.items())
        },
        "candidate_union_objects": len(candidate_union),
        "raw_union_objects": len(raw_union),
        "persisted_union_objects": len(persisted_union),
        "loss_mechanisms": {
            "electronics_or_digitization_not_in_any_candidate_readout": len(
                expected - candidate_union
            ),
            "available_only_in_trigger_rule_rejected_readouts": len(
                (expected & candidate_union) - raw_union
            ),
            "present_in_RAW_but_not_HLT_persisted": len(
                (expected & raw_union) - persisted_union
            ),
        },
        "missing_from_raw_union": len(expected - raw_union),
        "missing_from_persisted_union": len(expected - persisted_union),
        "raw_capture_classification": _capture_classification(
            expected, stored, candidate, raw, bx_split_offsets
        ),
        "persisted_capture_classification": _capture_classification(
            expected, stored, candidate, persisted, bx_split_offsets
        ),
    }


def _stage_result(
    expected, stored, candidate, raw, persisted, split_subsystems=False,
    bx_split_evidence=None,
):
    bx_split_evidence = bx_split_evidence or {}
    result = _stage_metrics(
        expected, stored, candidate, raw, persisted, set(bx_split_evidence)
    )
    if bx_split_evidence:
        result["within_readout_bx_split_evidence"] = {
            str(offset): evidence
            for offset, evidence in sorted(bx_split_evidence.items())
        }
    if split_subsystems:
        subsystems = sorted(
            {item[0] for item in expected}
            | {item[0] for values in stored.values() for item in values}
        )
        result["subsystems"] = {}
        for subsystem in subsystems:
            subsystem_expected = {item for item in expected if item[0] == subsystem}
            subsystem_stored = {
                offset: {item for item in items if item[0] == subsystem}
                for offset, items in stored.items()
            }
            subsystem_split_offsets = {
                offset
                for offset, evidence in bx_split_evidence.items()
                if len(evidence.get(subsystem, [])) > 1
            }
            result["subsystems"][subsystem] = _stage_metrics(
                subsystem_expected, subsystem_stored, candidate, raw, persisted,
                subsystem_split_offsets,
            )
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("timeline", help="rule-enabled ordinary-trigger timeline JSONL")
    parser.add_argument(
        "--capture", action="append", default=[], metavar="OFFSET=JSON",
        help="truth-linked digi/RAW response at a signal BX offset; repeat for the grid",
    )
    parser.add_argument(
        "--trigger", action="append", default=[], metavar="OFFSET=JSON",
        help="CSC/regional trigger response at the same offset; repeat for the grid",
    )
    parser.add_argument(
        "--response-dir", type=Path,
        help="discover capture.json and trigger_funnel.json point reports below this grid directory",
    )
    parser.add_argument(
        "--phase-ns", type=float, default=0.0,
        help="select this intra-BX phase from the response grid (default: 0)",
    )
    parser.add_argument("--output", required=True)
    parser.add_argument(
        "--allow-all-colliding-fixture", action="store_true",
        help="development only: allow a timeline without a versioned colliding-BX mask",
    )
    parser.add_argument(
        "--allow-incomplete-grid", action="store_true",
        help="development only: report rather than reject uncovered candidate L1A BXs",
    )
    args = parser.parse_args()

    if not 0.0 <= args.phase_ns < 25.0:
        parser.error("--phase-ns must be in [0, 25)")
    if args.response_dir:
        args.capture.extend(
            _discover_response_specs(args.response_dir, "capture.json", args.phase_ns)
        )
        args.trigger.extend(
            _discover_response_specs(
                args.response_dir, "trigger_funnel.json", args.phase_ns
            )
        )
    if not args.capture:
        parser.error("pass --capture or --response-dir")

    capture_reports, capture_paths = _load_reports(
        args.capture, 2, "capture", args.phase_ns
    )
    capture_index = _validate_response_identity(capture_reports, "capture")
    capture_indices = {
        offset: _index_muons(report) for offset, report in capture_reports.items()
    }
    trigger_reports, trigger_paths = _load_reports(
        args.trigger, 1, "trigger", args.phase_ns
    )
    trigger_index = None
    if trigger_reports:
        if set(trigger_reports) != set(capture_reports):
            raise RuntimeError("capture and trigger response offsets must be identical")
        trigger_index = _validate_response_identity(trigger_reports, "trigger")
        trigger_indices = {
            offset: _index_muons(report) for offset, report in trigger_reports.items()
        }
        if [set(event) for event in trigger_index] != [set(event) for event in capture_index]:
            raise RuntimeError("capture and trigger reports have different signal identities")

    timeline_metadata, timeline_records = _load_timeline(args.timeline)
    if not timeline_metadata.get("trigger_rules_applied"):
        raise RuntimeError("final capture classification requires a rule-enabled timeline")
    if (
        not timeline_metadata.get("colliding_bx_mask")
        and not args.allow_all_colliding_fixture
    ):
        raise RuntimeError(
            "final capture classification requires a versioned colliding-BX file; "
            "use --allow-all-colliding-fixture only for a software mechanism test"
        )
    if len(capture_index) != int(timeline_metadata["signal_events"]):
        raise RuntimeError("response event count does not match timeline signal_events")

    output_events = []
    summary = defaultdict(int)
    for event_index, reference_muons in enumerate(capture_index):
        candidate, raw, persisted, readouts, uncovered = _readout_sets(
            timeline_records[event_index],
            set(capture_reports),
            allow_incomplete_grid=args.allow_incomplete_grid,
        )
        event_result = {
            "signal_event_index": event_index,
            "candidate_response_offsets": sorted(candidate),
            "raw_response_offsets": sorted(raw),
            "persisted_response_offsets": sorted(persisted),
            "ordinary_trigger_readouts": readouts,
            "uncovered_candidate_timeline_bx": sorted(set(uncovered)),
            "signal_muons": [],
        }
        for key in sorted(reference_muons):
            capture_muons = {
                offset: capture_indices[offset][event_index][key]
                for offset in capture_reports
            }
            expected, stored = _stage_sets(
                capture_muons, "linked_channels", "matched_channels", _digi_spatial_channels
            )
            digi_result = _stage_result(
                expected, stored, candidate, raw, persisted,
                split_subsystems=True,
                bx_split_evidence=_digi_bx_split_evidence(capture_muons),
            )
            summary[digi_result["persisted_capture_classification"]] += 1
            muon_result = {
                "run": key[0], "lumi": key[1], "event": key[2],
                "event_id_raw": key[3], "track_id": key[4],
                "digi_RAW": digi_result,
            }
            if trigger_index is not None:
                trigger_muons = {
                    offset: trigger_indices[offset][event_index][key]
                    for offset in trigger_reports
                }
                lct_expected, lct_stored = _stage_sets(
                    trigger_muons,
                    "compatible_prepack_LCTs",
                    "matched_unpacked_LCTs",
                    _lct_spatial_channels,
                )
                muon_result["CSC_LCT_RAW"] = _stage_result(
                    lct_expected, lct_stored, candidate, raw, persisted
                )
            event_result["signal_muons"].append(muon_result)
        if trigger_reports:
            event_result["regional_candidates_by_response_offset"] = {
                str(offset): report["events"][event_index]["regional_candidate_bx_counts"]
                for offset, report in sorted(trigger_reports.items())
            }
        output_events.append(event_result)

    physics_blockers = []
    if not timeline_metadata.get("colliding_bx_mask"):
        physics_blockers.append("timeline has no versioned colliding-bunch mask")
    rule_status = (timeline_metadata.get("trigger_rules") or {}).get("status")
    if rule_status != "validated":
        physics_blockers.append(f"trigger-rule status is {rule_status or 'unknown'}")
    run_fill_status = (
        timeline_metadata.get("run_fill_validation") or {}
    ).get("status")
    if run_fill_status != "validated":
        physics_blockers.append(
            f"trigger-run-to-fill status is {run_fill_status or 'unknown'}"
        )
    physics_blockers.append("SHIFT-specific HLT object and first-failing-module closure is pending")

    output = {
        "schema_version": 1,
        "physics_result_valid": not physics_blockers,
        "physics_validation_blockers": physics_blockers,
        "validated_operation": (
            "convolution of independently measured fixed detector-response points with "
            "rule-accepted ordinary-trigger readout BXs"
        ),
        "coordinate_convention": (
            "timeline readout BX b selects response signal_bx_offset = -b"
        ),
        "response_phase_ns": args.phase_ns,
        "capture_responses": {str(key): value for key, value in sorted(capture_paths.items())},
        "trigger_responses": {str(key): value for key, value in sorted(trigger_paths.items())},
        "timeline": args.timeline,
        "timeline_metadata": timeline_metadata,
        "limitations": [
            "Expected objects are the union digitizable over the supplied response grid.",
            "CSC LCT association is chamber-compatible rather than exact SimTrack association.",
            "Regional/uGMT candidates are event-global and are not assigned to a SHIFT muon.",
            "HLT persistence uses the sampled central event's accepted-path record; SHIFT HLT-object closure is pending.",
            "One explicit intra-BX phase is classified per output report.",
            "split_within_readout is inferred only from RPC/GEM digi BX values; DT TDC and CSC time-bin closure remain separate.",
        ],
        "events": output_events,
        "summary": {"persisted_digi_RAW_classifications": dict(sorted(summary.items()))},
    }
    with open(args.output, "w", encoding="utf-8") as output_file:
        json.dump(output, output_file, indent=2, sort_keys=True)
        output_file.write("\n")
    print(json.dumps(output["summary"], sort_keys=True))


if __name__ == "__main__":
    main()
