#!/usr/bin/env python3
"""Freeze the authorized larger-chunk QCD and independent binned J/psi pilot."""
import argparse
import json
from pathlib import Path
import subprocess
import sys


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('output', type=Path)
    p.add_argument('--template', type=Path, required=True)
    p.add_argument('--base', type=Path, default=Path('/eos/home-j/jniedzie/shift_cmssw'))
    args = p.parse_args()
    root = args.output.resolve()
    scripts = Path(__file__).resolve().parent
    subprocess.run([sys.executable, str(scripts/'prepare_sampling_scan.py'), str(root),
                    '--template', str(args.template.resolve())], check=True)
    ledgers = []
    for lo, hi in ((1, 2), (2, 5), (5, 10)):
        source = args.base/'qcd'/f'SamplingScan_qcdmu_pThat_{lo}to{hi}_scan_20260921_v1'/'sampling_pilot/gen/part0000/report.json'
        ledger = root/f'qcd_{lo}to{hi}_ledger.json'
        subprocess.run([sys.executable, str(scripts/'prepare_weighted_sampling.py'), str(source),
                        '--output', str(ledger), '--attempts', '5000', '--chunk-size', '50'], check=True)
        ledgers.append(str(ledger))
    subprocess.run([sys.executable, str(scripts/'validate_sampling_ledger.py'), *ledgers,
                    '--output', str(root/'ledger_audit.json')], check=True)
    subprocess.run([sys.executable, str(scripts/'prepare_replay_jobs.py'), str(root),
                    '--tag', 'p10floor0p1_5k_chunk50', '--seed-base', '9440000',
                    '--stage-timeout', '21600'], check=True)
    lines = []
    for index, (lo, hi) in enumerate(((1, 2), (2, 5), (5, 10), (10, 20), (20, -1))):
        for chunk in range(20):
            lines.append(f'jpsi full {lo} {hi} 50 {9540000+1000*index+chunk} {chunk} analysis1k_chunk50')
    (root/'jpsi.jobs').write_text('\n'.join(lines)+'\n')
    submit = (root/'full.sub').read_text().replace('/full.jobs', '/jpsi.jobs')
    submit = submit.replace('getenv = True', 'getenv = True\nenvironment = "SAMPLING_STAGE_TIMEOUT_SECONDS=21600"')
    (root/'jpsi.sub').write_text(submit)
    planned = [args.base/'qcd'/e['campaign'] for e in json.loads((root/'replay_manifest.json').read_text())]
    planned += [args.base/'jpsi'/f'SamplingScan_jpsi_pThat_{lo}to{hi}_analysis1k_chunk50_20260921_v1'
                for lo, hi in ((1, 2), (2, 5), (5, 10), (10, 20), (20, -1))]
    # Create shared parents once on the submit host; worker chunk directories
    # remain exclusive. Refuse any campaign already containing ROOT/report data.
    for campaign in planned:
        if campaign.exists():
            raise ValueError(f'Campaign already exists: {campaign}')
    for campaign in planned:
        for sub in ('sampling_replay', 'sampling_pilot/full', 'samples/step1', 'samples/step2',
                    'samples/step3', 'samples/step4', 'configs/step1', 'configs/step2',
                    'configs/step3', 'configs/step4', 'logs'):
            (campaign/sub).mkdir(parents=True, exist_ok=True)
    manifest = dict(schema='shift-expanded-sampling-v1', qcd_parent_attempts=15000,
        qcd_selected_events=sum(json.loads(Path(p).read_text())['selected_events'] for p in ledgers),
        qcd_chunk_size=50, qcd_seed_base=9440000, jpsi_events_per_bin=1000,
        jpsi_total_attempts=5000, jpsi_chunk_size=50, jpsi_seed_base=9540000,
        frozen_workflow=str(root/'workflow'), campaigns=[str(p) for p in planned],
        submit_files=['replay.sub', 'jpsi.sub'],
        unused_default_scan_manifests='Do not submit smoke/gen/full/scan.sub generated by the generic freezer.',
        qcd_overlap_warning='Includes the old 500-attempt prefixes. Replacement/benchmark, not independent additive QCD statistics.',
        physics_valid=False, normalization_ready=False, geometry='IR1/ATLAS proxy',
        detector_settings_changed=False, reconstructed_mass_read=False)
    (root/'expanded_manifest.json').write_text(json.dumps(manifest, indent=2)+'\n')
    print(json.dumps(manifest, indent=2))


if __name__ == '__main__':
    main()
